import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <>
          <NavigationBar />
          {children}
        </>
      </body>
    </html>
  );
}


function NavigationBar() {
  return (
    <>
      <ul class="flex">
        <li class="mr-6">
          <Link href="/">Home</Link>
        </li>
        <li class="mr-6">
          <Link href="/peg-puzzle-classic">Peg Puzzle Classic</Link>
        </li>
        <li class="mr-6">
          <Link href="/guitar-tuner">Guitar Tuner</Link>
        </li>
      </ul>
    </>
  )
}
